import 'package:sahibz_inventory_management_system/models/recent_activity.dart';
import 'package:sahibz_inventory_management_system/services/core_service.dart';
import 'package:sahibz_inventory_management_system/models/expense.dart';

/// Service class for managing expense records and their database operations.
///
/// This service provides a high-level API for expense CRUD operations,
/// wrapping the [CoreService] with expense-specific functionality.
///
/// Features:
/// - Count total expense entries
/// - Calculate sum of all expenses
/// - Retrieve all expense records
/// - Insert new expense records
/// - Update existing expense records
/// - Delete expense records
///
/// All operations automatically log activities to the recent activity table
/// for audit purposes. The [totalExpenses] method provides aggregate calculations
/// for financial reporting.
///
/// Usage:
/// ```dart
/// final service = ExpenseService();
/// final count = await service.count();
/// final total = await service.totalExpenses();
/// final expenses = await service.getAll();
/// await service.insert(expense: newExpense);
/// ```
class ExpenseService {
  /// Core service instance configured for the 'expense' table.
  ///
  /// Provides the underlying CRUD operations with automatic activity logging.
  final CoreService core = CoreService(tableName: 'expense');

  /// Counts the total number of expense entries.
  /// Returns a [Future] that completes with the total count of expense entries.
  Future<int> count() async {
    return await core.countTotal();
  }

  /// Calculates the sum of all expense amounts.
  ///
  /// Returns a [Future] that completes with the total sum of all expense amounts,
  /// or 0 if no expenses exist. This is useful for financial reporting and
  /// dashboard summaries.
  Future<num> totalExpenses() async {
    return await core.totalExpenses();
  }

  /// Retrieves all expense records from the database.
  ///
  /// Returns a [Future] that completes with a list of maps containing
  /// all expense records. Use [Expense.fromJson] to convert to model objects.
  Future<List<Map<String, Object?>>> getAll() async {
    return await core.getAll();
  }

  /// Inserts a new expense record.
  ///
  /// [expense] - The [Expense] object to insert. The ID field is automatically
  /// removed as it is generated by the database.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> insert({required Expense expense}) async {
    Map<String, Object?> data = expense.toJson();
    data.remove('id');
    return await core.insert(data: data, type: RecentActivityType.expenseAdded);
  }

  /// Updates an existing expense record.
  ///
  /// [id] - The ID of the expense record to update.
  /// [expense] - The [Expense] object with updated values.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> update({
    required int id,
    required Expense expense,
    String? idColumnName,
  }) async {
    return await core.update(
      id: id,
      data: expense.toJson(),
      idColumnName: idColumnName,
      type: RecentActivityType.expenseUpdated,
    );
  }

  /// Deletes an expense record.
  ///
  /// [id] - The ID of the expense record to delete.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> delete({required int id, String? idColumnName}) async {
    return await core.delete(
      id: id,
      idColumnName: idColumnName,
      type: RecentActivityType.expenseRemoved,
    );
  }
}
