import 'package:sahibz_inventory_management_system/models/recent_activity.dart';
import 'package:sahibz_inventory_management_system/services/core_service.dart';
import 'package:sahibz_inventory_management_system/models/inventory.dart';

/// Service class for managing inventory items and their database operations.
///
/// This service provides a high-level API for inventory CRUD operations,
/// wrapping the [CoreService] with inventory-specific functionality.
///
/// Features:
/// - Count total inventory items
/// - Retrieve all inventory items
/// - Insert new inventory items (with auto-generated labels)
/// - Update existing inventory items
/// - Delete inventory items
///
/// All operations automatically log activities to the recent activity table
/// for audit purposes.
///
/// Usage:
/// ```dart
/// final service = InventoryService();
/// final count = await service.count();
/// final items = await service.getAll();
/// await service.insert(inventory: newItem);
/// ```
class InventoryService {
  /// Core service instance configured for the 'inventory' table.
  ///
  /// Provides the underlying CRUD operations with automatic activity logging.
  final CoreService core = CoreService(tableName: 'inventory');

  /// Counts the total number of inventory items.
  /// 
  /// Returns a [Future] that completes with the total count of inventory items.
  Future<int> count() async {
    return await core.countTotal();
  }

  /// Retrieves all inventory items from the database.
  ///
  /// Returns a [Future] that completes with a list of maps containing
  /// all inventory records. Use [Inventory.fromJson] to convert to model objects.
  Future<List<Map<String, Object?>>> getAll() async {
    return await core.getAll();
  }

  /// Inserts a new inventory item.
  ///
  /// [inventory] - The [Inventory] object to insert. The ID and label fields
  /// are automatically removed as they are generated by the database.
  ///
  /// The database automatically generates a unique 8-character alphanumeric label.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> insert({required Inventory inventory}) async {
    Map<String, Object?> data = inventory.toJson();
    data.remove('id');
    data.remove('label');
    return await core.insert(
      data: data,
      type: RecentActivityType.inventoryAdded,
    );
  }

  /// Updates an existing inventory item.
  ///
  /// [id] - The ID of the inventory item to update.
  /// [inventory] - The [Inventory] object with updated values.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> update({
    required int id,
    required Inventory inventory,
    String? idColumnName,
  }) async {
    return await core.update(
      id: id,
      data: inventory.toJson(),
      idColumnName: idColumnName,
      type: RecentActivityType.inventoryUpdated,
    );
  }

  /// Deletes an inventory item.
  ///
  /// [id] - The ID of the inventory item to delete.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> delete({required int id, String? idColumnName}) async {
    return await core.delete(
      id: id,
      idColumnName: idColumnName,
      type: RecentActivityType.inventoryRemoved,
    );
  }
}
