import 'package:sahibz_inventory_management_system/database_helper.dart';
import 'package:sahibz_inventory_management_system/models/recent_activity.dart';
import 'package:sahibz_inventory_management_system/models/supplier.dart';
import 'package:sahibz_inventory_management_system/services/core_service.dart';

/// Service class for managing Supplier items and their database operations.
///
/// This service provides a high-level API for Supplier CRUD operations,
/// wrapping the [CoreService] with Supplier-specific functionality.
///
/// Features:
/// - Count total Supplier items
/// - Retrieve all Supplier items
/// - Insert new Supplier items (with auto-generated labels)
/// - Update existing Supplier items
/// - Delete Supplier items
///
/// All operations automatically log activities to the recent activity table
/// for audit purposes.
///
/// Usage:
/// ```dart
/// final service = SupplierService();
/// final count = await service.count();
/// final items = await service.getAll();
/// await service.insert(Supplier: newItem);
/// ```
class SupplierService {
  /// Core service instance configured for the 'Supplier' table.
  ///
  /// Provides the underlying CRUD operations with automatic activity logging.
  final CoreService core = CoreService(
    tableName: DatabaseHelper.instance.supplierTableName,
  );

  /// Counts the total number of Supplier items.
  ///
  /// Returns a [Future] that completes with the total count of Supplier items.
  Future<int> count() async {
    return await core.countTotal();
  }

  /// Retrieves all Supplier items from the database.
  ///
  /// Returns a [Future] that completes with a list of maps containing
  /// all Supplier records. Use [Supplier.fromJson] to convert to model objects.
  Future<List<Map<String, Object?>>> getAll() async {
    return await core.getAll();
  }

  /// Inserts a new Supplier item.
  ///
  /// [Supplier] - The [Supplier] object to insert. The ID and label fields
  /// are automatically removed as they are generated by the database.
  ///
  /// The database automatically generates a unique 8-character alphanumeric label.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> insert({required Supplier supplier}) async {
    Map<String, Object?> data = supplier.toJson();
    data.remove('id');
    return await core.insert(
      data: data,
      type: RecentActivityType.supplierAdded,
    );
  }

  /// Updates an existing Supplier item.
  ///
  /// [id] - The ID of the Supplier item to update.
  /// [Supplier] - The [Supplier] object with updated values.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> update({
    required int id,
    required Supplier supplier,
    String? idColumnName,
  }) async {
    return await core.update(
      id: id,
      data: supplier.toJson(),
      idColumnName: idColumnName,
      type: RecentActivityType.supplierUpdated,
    );
  }

  /// Deletes an Supplier item.
  ///
  /// [id] - The ID of the Supplier item to delete.
  /// [idColumnName] - Optional custom column name for the ID field.
  ///
  /// Returns a [Future] that completes with the ID of the activity log entry.
  Future<int> delete({required int id, String? idColumnName}) async {
    return await core.delete(
      id: id,
      idColumnName: idColumnName,
      type: RecentActivityType.supplierRemoved,
    );
  }
}