// ignore_for_file: use_build_context_synchronously

import 'dart:io';
import 'dart:math';

import 'package:flutter/cupertino.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:sahibz_inventory_management_system/database_helper.dart';
import 'package:sahibz_inventory_management_system/dialogs/error_dialog.dart';
import 'package:sahibz_inventory_management_system/sahibz_inventory_management_system.dart';
import 'package:sahibz_inventory_management_system/utils/datetime_formatter.dart';
import 'package:sahibz_inventory_management_system/utils/flutter_storage_setter.dart';

Future<void> exportToPdf({
  required BuildContext context,
  required DatabaseTableNames tableName,
  required List<Map<String, dynamic>> rows,
  required String fileName,
  required FlutterStorageSetter storageSetter,
}) async {
  // final List<Map<String, dynamic>> rows = await CoreService(
  //   tableName: tableName,
  // ).getAll();
  if (rows.isEmpty) {
    ErrorDialog(
      context: context,
      error: 'No data found to export',
      storageSetter: storageSetter,
    );
    return;
  }
  final DateTimeParserEnum? parserEnum = await storageSetter
      .getDateTimeParserStorageEnum();

  if (parserEnum == null) {
    ErrorDialog(
      context: context,
      error: 'DateTime parser enum not found',
      storageSetter: storageSetter,
    );
    return;
  }

  final pdf = pw.Document();
  final columnCount = rows.first.keys.length;
  final double fontSize = 10.0 - min(columnCount / 5, 1).roundToDouble();
  final double cellPadding = 5.0;

  final table = pw.Table(
    border: pw.TableBorder.all(width: 1.2, color: PdfColors.black),
    children: [
      pw.TableRow(
        decoration: .new(color: PdfColors.grey200),
        children: [
          for (final columnName in rows.first.keys)
            pw.Container(
              padding: pw.EdgeInsets.all(cellPadding),
              child: pw.Text(
                columnName.customizeHeaderTableTitles().toUpperCase(),
                textAlign: .center,
                style: pw.TextStyle(
                  fontSize: fontSize,
                  letterSpacing: 1.0,
                  fontWeight: .bold,
                ),
              ),
            ),
        ],
      ),
      for (final row in rows)
        pw.TableRow(
          children: [
            for (final key in row.keys)
              pw.Container(
                padding: pw.EdgeInsets.all(cellPadding),
                child: pw.Text(
                  row[key].toString().isEmpty
                      ? 'null'
                      : DateTime.tryParse(row[key].toString()) != null
                      ? convertDateTimeString2Formatted(
                          DateTime.parse(row[key].toString()),
                          parserEnum,
                        )
                      : row[key].toString(),
                  textAlign: .center,
                  style: pw.TextStyle(fontSize: fontSize),
                ),
              ),
          ],
        ),
    ],
    tableWidth: .min,
    defaultVerticalAlignment: .middle,
    columnWidths: {
      for (int i = 0; i < columnCount; i++)
        i: pw.FractionColumnWidth(1 / columnCount),
    },
  );
  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a3,
      build: (pw.Context context) {
        return [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: .spaceBetween,
              children: [
                pw.Text(
                  '${tableName.value.customizeHeaderTableTitles()} Table',
                  textScaleFactor: 2,
                ),
                pw.Padding(
                  padding: pw.EdgeInsets.only(top: 20),
                  child: pw.Text(
                    "Generated at: ${convertDateTimeString2Formatted(DateTime.now(), parserEnum)}",
                    textAlign: pw.TextAlign.right,
                    style: pw.TextStyle(fontSize: 10),
                  ),
                ),
              ],
            ),
          ),
          table,
        ];
      },
      orientation: .portrait,
      footer: (pw.Context context) {
        return pw.Row(
          children: [
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              textAlign: pw.TextAlign.center,
              style: pw.TextStyle(fontSize: 10),
            ),
            pw.Expanded(
              child: pw.Text(
                'Generated by SAHIBZ INVENTORY SYSTEM',
                textAlign: pw.TextAlign.right,
                style: pw.TextStyle(fontSize: 10),
              ),
            ),
          ],
        );
      },
    ),
  );

  final filePath = './$fileName.pdf';
  final file = File(filePath);
  await file.writeAsBytes(await pdf.save());
}
