List<String> expenseType = [
  'Operating Expenses',
  'Capital Expenses',
  'Discretionary Expenses',
  'Fixed Expenses',
  'Variable Expenses',
  'One-Time Expenses',
  'Recurring Expenses',
  'Contingency Expenses',
  'Emergency Expenses',
  'Other Expenses',
  'Salaries and Wages',
  'Rent',
  'Utilities',
  'Marketing',
  'Insurance',
  'Taxes',
  'Software',
  'Hardware',
  'Maintenance',
  'Repairs',
  'Training',
  'Travel',
  'Entertainment',
  'Office Supplies',
  'Communication',
  'Transportation',
  'Legal',
  'Professional Services',
  'Consulting',
  'Advertising',
  'Public Relations',
  'Events',
  'Charity',
  'Donations',
  'Research and Development',
  'Improvements',
  'Upgrades',
  'Renovations',
  'Leases',
  'Licenses',
  'Subscriptions',
  'Memberships',
  'Software Licenses',
  'Hardware Licenses',
  'Cloud Services',
  'Hosting',
  'Domain Names',
  'Email Services',
  'Security Services',
  'Backup Services',
  'Data Services',
  'Analytics Services',
  'Reporting Services',
  'Integration Services',
  'API Services',
  'Third-Party Services',
  'Miscellaneous',
];
